apiVersion: v1
kind: Service
metadata:
  name: todo-django-service
spec:
  type: NodePort
  selector:
    app: todo-django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008  # Specify a port within the allowed range (30000-32767)
  
