apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  #MYSQL_HOST: MTAuOTguMTkuMjEx  # base64 encoded "10.98.19.211"
  MYSQL_PASSWORD: YWRtaW4=       # base64 encoded "admin"
  MYSQL_USER: YWRtaW4=           # base64 encoded "admin"
  MYSQL_DB: bXlkYg==             # base64 encoded "mydb"



